version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "6831:6831/udp" # Jaeger agent UDP port (for Thrift compact protocol)
      - "6832:6832/udp" # Jaeger agent UDP port (for Thrift binary protocol)
      - "5778:5778"     # Jaeger agent HTTP endpoint (for configuration)
      - "4317:4317"     # Jaeger gRPS HTTP collector
      - "4318:4318"     # Jaeger gRPS HTTP collector (encrypted)
      - "14250:14250"     # Jaeger gRPS tracing
      - "14268:14268"     # Jaeger gRPS HTTP internal service communication
      - "14269:14269"     # Jaeger gRPS HTTP internal service communication (encrypted)
      - "9411:9411"     # Collector zipkin

    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - jaeger-network

networks:
  jaeger-network:
    driver: bridge