pub const CREATE_PHONE_TYPE: &str = r#"
CREATE TYPE phone_type_enum AS ENUM ('Email', 'Phone');
"#;

pub const CREATE_USER_TABLE: &str = r#"
CREATE TABLE "users" (
  id BIGINT GENERATED BY DEFAULT AS phone PRIMARY KEY,

  phone varchar(128) NOT NULL UNIQUE,
  phone_type phone_type_enum,

  first_name varchar(128) NOT NULL,
  last_name varchar(128),

  -- Auth
  pwd varchar(256),
  pwd_salt varchar(128) NOT NULL ,
  token_salt varchar(128) NOT NULL,

  -- Timestamps
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);
"#;