CREATE TABLE IF NOT EXISTS "users" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  phone varchar(128) NOT NULL UNIQUE,

  first_name varchar(128) NOT NULL,
  last_name varchar(128),

  -- Auth
  pwd varchar(256),
  pwd_salt UUID NOT NULL ,
  token_salt UUID NOT NULL,

  -- Timestamps
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);
