CREATE TABLE IF NOT EXISTS "book_info" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  title varchar(128) NOT NULL UNIQUE,
  author varchar(256),
  isbn varchar(128) NOT NULL UNIQUE,
  description TEXT,

    -- Timestamps
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);
