CREATE TYPE order_status AS ENUM ('new', 'in_progress', 'ready_to_deliver', 'delivered');

CREATE TABLE IF NOT EXISTS "order_info" (
  order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  content JSON NOT NULL,
  status order_status NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);
